# Generated by Django 5.0.1 on 2024-01-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='createdAt',
            field=models.DateField(null=True),
        ),
    ]
